version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crypto_portfolio
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=crypto_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crypto_user -d crypto_portfolio"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - crypto-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - DATABASE_URL=postgresql://crypto_user:crypto_secure_password_2024@postgres:5432/crypto_portfolio
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/cryptassist/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - crypto-network

volumes:
  postgres_data:
    driver: local

networks:
  crypto-network:
    name: crypto-assistant-network