version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/cryptassist/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - backend_data:/app/data

volumes:
  backend_data:
    driver: local

networks:
  default:
    name: crypto-assistant-backend